import React, { useEffect, useState } from "react";
import i from "./InstructorCourseCreate.module.css";
import InstructorTopBar from "../../../components/InstructorTopBar/InstructorTopBar";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import { api } from "../../../api";

export default function InstructorCourseCreate({ onCourseCreated }) {
  const navigate = useNavigate();
  const [lessons, setLessons] = useState([]);
  const [showModal, setShowModal] = useState(false);
  const [lessonInput, setLessonInput] = useState("");
  const [showOptionalModal, setShowOptionalModal] = useState(false);
  const [lessonsNumber, setLessonsNumber] = useState(0)
  const [submitting, setSubmitting] = useState(false); //Guarding number of course submission 
  
  const [formData, setFormData] = useState({
    title: "",
    course_id: "",
    director: "",
    description: "",
    status: "Active", 
  });


  const openModal = () => {
    setShowModal(true);
  };

  const openModal1 = (e) => {
    e.preventDefault();
    setShowOptionalModal(true);
  };

  const closeModal = () => {
    setLessonInput("");
    setShowModal(false);
  };

  const addLesson = () => {
    if (lessonInput.trim() !== "") {
      setLessons([...lessons, lessonInput.trim()]);
      closeModal();
    }
  };

  const goToCoursePage = () => {
    setShowOptionalModal(false);
    navigate("/instructor/course-list");
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: value });
  };

  const resetForm = () => {
    setFormData({
      title: "",
      course_id: "",
      director: "",
      description: "",
      status: "Active",
    });
    setLessons([]);
    setLessonInput("");
    setLessonsNumber(0);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (submitting) return;           // guard
    setSubmitting(true);

    const code = (formData.course_id || "").trim();

      // Prepare data for Django backend
      try {
        // Prepare data for Django backend
        const courseData = {
          title: formData.title,
          credits: 30,
          owner_instructor_email: (formData.director) || undefined,
          description: formData.description,
          status: formData.status, //Newly added here, check serializer again
          ...(code ? { course_id: code } : {}),
        };

  
      // Send to Django backend
      const createRes = await api.post("/instructor/courses/", courseData);
      console.log("Course created successfully:", courseData);
      const cid = createRes.data?.course_id; // use server’s generated/normalized id

      const n = parseInt(lessonsNumber, 10);
      if (!Number.isInteger(n) || n < 1) {
        alert("Enter a valid number of lessons (>=1).");
        return;
      } //Validate lessons number

      //Send lessons number here 
      await api.post(`/instructor/courses/${cid}/lessons/bulk-create/`, {
        count: Number(lessonsNumber),
        credits: 0,
        base_title: "Lesson",
        starting_number: 1,
        duration_weeks: 4,
        status: "Inactive",
        description: "",
        objectives: ""
      });

      // Refresh the course list in parent component
      if (onCourseCreated) {
        onCourseCreated();
      }

      // Show success modal
      setShowOptionalModal(true);
    } catch (error) {
      console.error("Error creating course:", error);
      alert("Error creating course. Please try again.");
    }
  };
 
  return (
    <div className={i.wrap}>
      <div className={i.topBar}>
        <InstructorTopBar />
      </div>
      <header className={i.header}>
        <h1 className={i.title}>COURSE CREATION</h1>
      </header>
      <div>
        <form className={i.form} onSubmit={handleSubmit}>
          <div className={i.formContainer}>
            <div className={i.row}>
              <label className={i.label}>Course Details</label>
            </div>
            <div className={i.row}>
              <label className={i.label} htmlFor="title">
                Course Title:
              </label>
              <input
                id="title"
                className={i.input}
                type="text"
                name="title"
                value={formData.title}
                onChange={handleChange}
                required
              />
            </div>

            <div className={i.row}>
              <label className={i.label} htmlFor="course_id">
                Course Code:
              </label>
              <input
                id="course_id"
                placeholder="Autogenerated if empty"
                className={i.input}
                type="text"
                name="course_id"
                value={formData.course_id}
                onChange={handleChange}
              />
            </div>

            <div className={i.row}>
              <span className={i.label}>Course Credits:</span>
              <div className={i.creditsDisplay}>30 Credits</div>
              <input id="credits" type="hidden" name="credits" value={30} />
            </div>

            <div className={i.row}>
              <label className={i.label} htmlFor="director">
                Course Director:
              </label>
              <input
                id="director"
                className={i.input}
                placeholder="Input Instructor email. Default to current instructor if empty"
                type="text"
                name="director"
                value={formData.director}
                onChange={handleChange}
              />
            </div>

            <div className={i.row}>
              <label className={i.label} htmlFor="description">
                Description:
              </label>
              <textarea
                id="description"
                className={i.input}
                name="description"
                value={formData.description}
                onChange={handleChange}
                required
              />
            </div>

            <div className={i.row}>
              <label className={i.label} htmlFor="number_of_lessons">
                Number of Lessons:
              </label>
              <input
                id="number_of_lessons"
                className={i.input}
                type="number"
                name="number_of_lessons"
                min="1"
                value={lessonsNumber}
                onChange={(e) => setLessonsNumber(e.target.value)}
                required
              />

              <label className={i.label} htmlFor="status">
                Course Status:
              </label>
              <div className={i.selectWrap}>
                <select
                  id="status"
                  name="status"
                  className={i.select}
                  value={formData.status}
                  onChange={handleChange}
                  required
                >
                  <option value="Active">Active</option>
                  <option value="Inactive">Inactive</option>
                </select>
                
              </div>
            </div>

            <div className={i.rowBlock}>
             
    
              {showModal && (
                <div className={i.modalOverlay}>
                  <div className={i.modalContent}>
                    <h3>Add Core Lesson</h3>
                    <input
                      type="text"
                      value={lessonInput}
                      onChange={(e) => setLessonInput(e.target.value)}
                      className={i.input}
                      placeholder="Enter lesson name"
                    />
                    <div className={i.modalButtons}>
                      <button className={i.selectButton} onClick={addLesson}>
                        Select
                      </button>
                      <button className={i.cancelButton} onClick={closeModal}>
                        Cancel
                      </button>
                    </div>
                  </div>
                </div>
              )}
            </div>

            {showOptionalModal && (
  <div className={i.modalOverlay}>
    <div className={i.modalContent}>
      <h3>Course Created Successfully!</h3>
      <div className={i.modalButtons}>
        <button
          type="button"
          className={i.selectButton}
          onClick={goToCoursePage}
        >
          Go to course page
        </button>
      </div>
    </div>
  </div>
)}

            <div className={i.buttonRow}>
              <button
                className={i.discardbutton}
                type="button"
                onClick={resetForm}
              >
                Discard
              </button>
              <button className={i.createbutton} type="submit">
                Create
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
}
