# Generated by Django 5.2.6 on 2025-09-24 02:24

import api.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='code', max_length=20, null=True, unique=True)),
                ('course_title', models.CharField(blank=True, db_column='title', max_length=255, null=True)),
                ('course_credits', models.PositiveIntegerField(db_column='credits', default=30, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('course_director', models.CharField(blank=True, db_column='director', max_length=50, null=True)),
                ('course_description', models.TextField(blank=True, db_column='description', null=True)),
                ('course_status', models.CharField(choices=[('Active', 'ACTIVE'), ('Inactive', 'INACTIVE'), ('Draft', 'DRAFT')], db_column='status', default='Active', max_length=50)),
                ('course_number_of_lessons', models.IntegerField(db_column='number_of_lessons', default=0)),
            ],
            options={
                'db_table': 'course',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('instructor_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'instructor_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('student_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('student_no', models.CharField(max_length=50, unique=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseDraft',
            fields=[
                ('draft_id', models.CharField(default=api.models.generate_custom_id, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('outline_json', models.JSONField(blank=True, null=True)),
                ('is_selected', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.course')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.instructorprofile')),
            ],
            options={
                'db_table': 'course_draft',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='owner_instructor',
            field=models.ForeignKey(blank=True, db_column='owner_instructor_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.instructorprofile'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.AutoField(db_column='lesson_id', primary_key=True, serialize=False)),
                ('lesson_title', models.CharField(blank=True, db_column='title', max_length=255, null=True)),
                ('lesson_description', models.TextField(blank=True, db_column='description', null=True)),
                ('lesson_objectives', models.TextField(blank=True, db_column='objectives', null=True)),
                ('lesson_duration_weeks', models.PositiveIntegerField(blank=True, choices=[(2, '2'), (3, '3'), (4, '4')], db_column='duration_weeks', default=4, null=True)),
                ('lesson_status', models.CharField(choices=[('Active', 'ACTIVE'), ('Inactive', 'INACTIVE'), ('Archived', 'ARCHIVED')], db_column='status', default='Active', max_length=50)),
                ('lesson_created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('lesson_prerequisite', models.TextField(blank=True, db_column='prerequisite', max_length=500, null=True)),
                ('courses', models.ForeignKey(blank=True, db_column='course_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.course')),
                ('lesson_created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.instructorprofile')),
            ],
            options={
                'db_table': 'lesson',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroom_id', models.AutoField(db_column='classroom_id', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='title', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('capacity', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('day_of_week', models.CharField(blank=True, max_length=20, null=True)),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.instructorprofile')),
                ('lesson', models.ForeignKey(blank=True, db_column='lesson_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.lesson')),
            ],
            options={
                'db_table': 'classroom',
                'managed': True,
                'unique_together': {('lesson', 'day_of_week', 'time_start', 'time_end')},
            },
        ),
        migrations.CreateModel(
            name='LessonEnrollment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.lesson')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.studentprofile')),
            ],
            options={
                'db_table': 'lesson_enrollment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClassroomEnrollment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.classroom')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.studentprofile')),
            ],
            options={
                'db_table': 'classroom_enrollment',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.user'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.user'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.course')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.studentprofile')),
            ],
            options={
                'db_table': 'enrollment',
                'managed': True,
                'unique_together': {('student', 'course')},
            },
        ),
    ]
