# Generated by Django 5.2.6 on 2025-09-23 16:03

import api.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_id",
                    models.CharField(
                        default=api.models.generate_custom_id,
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "ACTIVE"),
                            ("Inactive", "INACTIVE"),
                            ("Draft", "DRAFT"),
                        ],
                        default="Active",
                        max_length=50,
                    ),
                ),
                (
                    "credits",
                    models.PositiveIntegerField(default=30, editable=False, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "course",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InstructorProfile",
            fields=[
                (
                    "instructor_profile_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "staff_no",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
            ],
            options={
                "db_table": "instructor_profile",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "student_profile_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("student_no", models.CharField(max_length=50, unique=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "student_profile",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("role", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CourseDraft",
            fields=[
                (
                    "draft_id",
                    models.CharField(
                        default=api.models.generate_custom_id,
                        editable=False,
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("outline_json", models.JSONField(blank=True, null=True)),
                ("is_selected", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.instructorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "course_draft",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="course",
            name="owner_instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.instructorprofile",
            ),
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "lesson_id",
                    models.CharField(
                        default=api.models.generate_custom_id,
                        editable=False,
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("objectives", models.TextField(blank=True, null=True)),
                (
                    "duration_weeks",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(2, "2"), (3, "3"), (4, "4")],
                        default=4,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "ACTIVE"),
                            ("Inactive", "INACTIVE"),
                            ("Archived", "ARCHIVED"),
                        ],
                        default="Active",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.instructorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "lesson",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "classroom_id",
                    models.CharField(
                        default=api.models.generate_custom_id,
                        editable=False,
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("day_of_week", models.CharField(blank=True, max_length=20, null=True)),
                ("time_start", models.TimeField(blank=True, null=True)),
                ("time_end", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.instructorprofile",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.lesson",
                    ),
                ),
            ],
            options={
                "db_table": "classroom",
                "managed": True,
                "unique_together": {
                    ("lesson", "day_of_week", "time_start", "time_end")
                },
            },
        ),
        migrations.CreateModel(
            name="LessonPrerequisite",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.lesson",
                    ),
                ),
                (
                    "prereq_lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="lessonprerequisite_prereq_lesson_set",
                        to="api.lesson",
                    ),
                ),
            ],
            options={
                "db_table": "lesson_prerequisite",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LessonEnrollment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.lesson",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "lesson_enrollment",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ClassroomEnrollment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.classroom",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "classroom_enrollment",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.user",
            ),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.user",
            ),
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("enrollment_id", models.AutoField(primary_key=True, serialize=False)),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "enrollment",
                "managed": True,
                "unique_together": {("student", "course")},
            },
        ),
    ]
