# Generated by Django 5.2.6 on 2025-09-15 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InstructorProfile",
            fields=[
                (
                    "instructor_profile_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("staff_no", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "instructor_profile",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("course_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=50)),
                ("credits", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "owner_instructor",
                    models.ForeignKey(
                        db_column="owner_instructor_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.instructorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "course",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "student_profile_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("student_no", models.CharField(max_length=50, unique=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "student_profile",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.user",
            ),
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("enrollment_id", models.AutoField(primary_key=True, serialize=False)),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        db_column="course_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "enrollment",
                "managed": True,
                "unique_together": {("student", "course")},
            },
        ),
    ]
