# Generated by Django 5.2.6 on 2025-10-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="full_name",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
