# Generated by Django 5.2.6 on 2025-10-11 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='titled',
            new_name='title',
        ),
    ]
