# Generated by Django 5.2.6 on 2025-09-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="credit",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
