# Generated by Django 5.2.6 on 2025-09-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='credits',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddConstraint(
            model_name='lessonprerequisite',
            constraint=models.UniqueConstraint(fields=('lesson', 'prereq_lesson'), name='uq_lesson_prereq'),
        ),
    ]
