# Generated by Django 5.2.6 on 2025-10-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonclassroom',
            unique_together=set(),
        ),
    ]

