# Generated by Django 5.2.6 on 2025-09-17 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_title', models.CharField(max_length=250)),
                ('lesson_id', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
                ('lesson_credits', models.IntegerField()),
                ('lesson_description', models.TextField(max_length=1000)),
                ('lesson_objective', models.TextField(max_length=1000)),
                ('lesson_prerequisite', models.TextField(max_length=500)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.course')),
            ],
        ),
    ]
