# Generated by Django 5.2.6 on 2025-09-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="credits",
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
