# Generated by Django 5.2.6 on 2025-09-24 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_lesson_credit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="credit",
            new_name="credits",
        ),
    ]
