# Generated by Django 5.2.6 on 2025-09-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_duration',
            field=models.IntegerField(default=0),
        ),
    ]
