# Generated by Django 5.2.6 on 2025-10-20 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_lessonclassroom_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentassignmentprogress',
            old_name='completed',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='studentreadingprogress',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
