# Generated by Django 5.2.6 on 2025-09-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_course_director"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroomenrollment",
            name="student",
        ),
    ]
