# Generated by Django 5.2.6 on 2025-09-16 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_course_credits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="credits",
            field=models.PositiveIntegerField(
                blank=True,
                default=30,
                null=True,
                validators=[django.core.validators.MaxValueValidator(30)],
            ),
        ),
    ]
