# Generated by Django 5.2.6 on 2025-09-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_lesson_credits"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="lessonprerequisite",
            constraint=models.UniqueConstraint(
                fields=("lesson", "prereq_lesson"), name="uq_lesson_prereq"
            ),
        ),
    ]
