# Generated by Django 5.2.6 on 2025-09-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_courses_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseDraft",
            fields=[
                ("draft_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("outline_json", models.JSONField(blank=True, null=True)),
                ("is_selected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "course_draft",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("enrollment_id", models.AutoField(primary_key=True, serialize=False)),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "enrollment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InstructorProfile",
            fields=[
                (
                    "instructor_profile_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("staff_no", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "instructor_profile",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "student_profile_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("student_no", models.CharField(max_length=50, unique=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "student_profile",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"managed": False},
        ),
    ]
