# Generated by Django 5.2.5 on 2025-09-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_courses_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(max_length=1000),
        ),
    ]
