# Generated by Django 5.2.6 on 2025-10-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('instructor', 'instructor'), ('student', 'student'), ('admin', 'admin')], default='instructor', max_length=50),
        ),
    ]
