# Generated by Django 5.2.6 on 2025-10-03 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_studentprofile_full_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="student_no",
        ),
    ]
