# Generated by Django 5.2.6 on 2025-10-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_completed_studentassignmentprogress_is_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassignmentprogress',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studentreadingprogress',
            name='id',
        ),
        migrations.AddField(
            model_name='studentassignmentprogress',
            name='student_assignment_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='studentreadingprogress',
            name='student_reading_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
