# Generated by Django 5.2.6 on 2025-09-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lesson_lesson_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['slot_position']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='slot_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('courses', 'slot_position')},
        ),
    ]
