# Generated by Django 5.2.6 on 2025-09-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_lessonprerequisite_uq_lesson_prereq"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lessonprerequisite",
            name="uq_lesson_prereq",
        ),
        migrations.AddConstraint(
            model_name="lessonprerequisite",
            constraint=models.UniqueConstraint(
                fields=("lesson", "prereq_lesson"), name="uq_lesson_prereq"
            ),
        ),
    ]
