# Generated by Django 5.2.6 on 2025-09-19 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_classroomenrollment_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroomenrollment",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.studentprofile",
            ),
        ),
    ]
