# Generated by Django 5.2.6 on 2025-10-12 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='director',
        ),
    ]
