# Generated by Django 5.2.6 on 2025-09-17 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_course_credits"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="owner_instructor",
            field=models.ForeignKey(
                db_column="owner_instructor_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.instructorprofile",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                db_column="course_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.course",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                db_column="student_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.studentprofile",
            ),
        ),
        migrations.AlterField(
            model_name="instructorprofile",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.user",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.user",
            ),
        ),
    ]
