# Generated by Django 5.2.6 on 2025-09-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_classroomenrollment_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('Active', 'ACTIVE'), ('Inactive', 'INACTIVE'), ('Draft', 'DRAFT')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('Active', 'ACTIVE'), ('Inactive', 'INACTIVE'), ('Archived', 'ARCHIVED')], default='Active', max_length=50),
        ),
    ]
