# Generated by Django 5.2.6 on 2025-09-20 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_classroomenrollment_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="code",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="classroom",
            name="capacity",
            field=models.PositiveIntegerField(
                default=10,
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="credits",
            field=models.PositiveIntegerField(
                default=30,
                null=True,
                validators=[django.core.validators.MaxValueValidator(30)],
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "ACTIVE"),
                    ("Inactive", "INACTIVE"),
                    ("Draft", "DRAFT"),
                ],
                default="Active",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "ACTIVE"),
                    ("Inactive", "INACTIVE"),
                    ("Archived", "ARCHIVED"),
                ],
                default="Active",
                max_length=50,
            ),
        ),
    ]
