# Generated by Django 5.2.6 on 2025-09-21 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_lesson_options_lesson_slot_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='slot_position',
        ),
    ]
