# Generated by Django 5.2.6 on 2025-10-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_classroom_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
