# Generated by Django 5.2.6 on 2025-09-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_lesson_options_alter_lesson_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slot_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('courses', 'slot_index')},
        ),
    ]
