# Generated by Django 5.2.6 on 2025-10-12 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_classroom_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='full_name',
        ),
    ]
