# Generated by Django 5.2.6 on 2025-09-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_lesson_slot_index_alter_lesson_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='course',
            name='course_number_of_lessons',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='slot_index',
        ),
    ]
