# Generated by Django 5.2.6 on 2025-10-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_studentprofile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='duration_weeks',
        ),
        migrations.RemoveField(
            model_name='lessonassignment',
            name='points',
        ),
        migrations.AddField(
            model_name='lessonclassroom',
            name='duration_weeks',
            field=models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4')], default=2),
        ),
        migrations.AddField(
            model_name='lessonclassroom',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AddConstraint(
            model_name='lessonreading',
            constraint=models.UniqueConstraint(fields=('lesson', 'title', 'url'), name='uniq_lesson_title_url'),
        ),
    ]
