# Generated by Django 5.2.6 on 2025-09-20 08:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_course_course_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="id",
            field=models.CharField(
                default=api.models.generate_custom_id,
                editable=False,
                max_length=6,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="coursedraft",
            name="draft_id",
            field=models.CharField(
                default=api.models.generate_custom_id,
                editable=False,
                max_length=6,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="lesson_id",
            field=models.CharField(
                default=api.models.generate_custom_id,
                editable=False,
                max_length=6,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
