# Generated by Django 5.2.6 on 2025-09-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_classroom_id_alter_coursedraft_draft_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="duration_weeks",
            field=models.PositiveIntegerField(
                blank=True, choices=[(2, "2"), (3, "3"), (4, "4")], default=4, null=True
            ),
        ),
    ]
