# Generated by Django 5.2.6 on 2025-10-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_classroom_duration_weeks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='zoom_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
