# Generated by Django 5.2.6 on 2025-10-16 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_classroom_zoom_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('admin_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.user')),
            ],
            options={
                'db_table': 'admin_profile',
                'managed': True,
            },
        ),
    ]
