# Generated by Django 5.2.6 on 2025-09-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_lesson_duration_weeks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroom",
            name="duration_weeks",
        ),
        migrations.RemoveField(
            model_name="classroom",
            name="title",
        ),
        migrations.AddField(
            model_name="classroom",
            name="duration_label",
            field=models.CharField(blank=True, null=True),
        ),
    ]
