# Generated by Django 5.2.6 on 2025-09-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_classroom_duration_weeks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="duration_label",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
