# Generated by Django 5.2.6 on 2025-10-16 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_instructorprofile_title_adminprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonclassroom',
            old_name='director',
            new_name='supervisor',
        ),
    ]
