# Generated by Django 5.2.6 on 2025-10-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_director_lessonclassroom_supervisor'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lessonclassroom',
            constraint=models.CheckConstraint(condition=models.Q(('time_end__gt', models.F('time_start'))), name='lessonclassroom_time_end_after_start'),
        ),
    ]
