# Generated by Django 5.2.6 on 2025-09-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_remove_classroom_duration_label_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classroom",
            old_name="id",
            new_name="classroom_id",
        ),
    ]
