# Generated by Django 5.2.6 on 2025-10-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_lessonclassroom_lessonclassroom_time_end_after_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='is_online',
            field=models.BooleanField(),
        ),
    ]
