# Generated by Django 5.2.6 on 2025-10-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_classroom_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
