# Generated by Django 5.2.6 on 2025-09-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_rename_id_classroom_classroom_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="credits",
            field=models.PositiveIntegerField(default=30, editable=False, null=True),
        ),
    ]
