# Generated by Django 5.2.6 on 2025-10-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_classroom_is_online'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lessonassignment',
            constraint=models.UniqueConstraint(fields=('lesson', 'title'), name='uniq_lesson_title'),
        ),
    ]
