# Generated by Django 5.2.6 on 2025-10-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_lessonassignment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonassignment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonreading',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
