# Generated by Django 5.2.6 on 2025-10-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_lessonassignment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('Completed', 'COMPLETED'), ('Incomplete', 'INCOMPLETE')], default='Incomplete', max_length=50),
        ),
        migrations.AddField(
            model_name='lessonenrollment',
            name='status',
            field=models.CharField(choices=[('Completed', 'COMPLETED'), ('Incomplete', 'INCOMPLETE')], default='Incomplete', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('Active', 'ACTIVE'), ('Inactive', 'INACTIVE'), ('Draft', 'DRAFT')], default='Active', max_length=50),
        ),
    ]
