# Generated by Django 5.2.6 on 2025-10-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_enrollment_status_lessonenrollment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='estimated_effort',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
