"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.5.
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os
import sys
import dj_database_url  # ← added

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ──────────────────────────────────────────────────────────
# Security & environment
# ──────────────────────────────────────────────────────────
# Use env secret in prod; fall back to your dev key locally
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    default="django-insecure--)hhfofc+1(6y*&ue2=7dxb6*=*jk$d3pd@e6d@rky7h1_v8lw",
)

# Auto-disable DEBUG on Render (env var RENDER is present there)
DEBUG = 'RENDER' not in os.environ

# Allowed hosts: allow anything in dev; restrict to Render hostname in prod
ALLOWED_HOSTS = ["*"] if DEBUG else []
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Optional: CSRF trust for Render domain (safe default)
if not DEBUG and RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS = [f"https://{RENDER_EXTERNAL_HOSTNAME}"]

# ──────────────────────────────────────────────────────────
# REST / JWT (unchanged)
# ──────────────────────────────────────────────────────────
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny"
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "TIME_FORMAT": "%H:%M",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=700),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=700),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "USER_ID_FIELD": "user_id",
    "USER_ID_CLAIM": "user_id",
}

# ──────────────────────────────────────────────────────────
# Apps / Middleware
# ──────────────────────────────────────────────────────────
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "api",
    "rest_framework",
    "corsheaders",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ← added (must be right after SecurityMiddleware)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

APPEND_SLASH = True

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
# (ASGI is still available for gunicorn+uvicorn via backend.asgi)

# ──────────────────────────────────────────────────────────
# Database
# ──────────────────────────────────────────────────────────
# Use DATABASE_URL in prod; default to your local Postgres in dev
DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://myuser:mypassword@localhost:5432/lms_db',
        conn_max_age=600,
    )
}

# Use sqlite for tests (unchanged behavior)
if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(os.path.dirname(__file__), 'test_db.sqlite3'),
        }
    }

# ──────────────────────────────────────────────────────────
# Password validation (unchanged)
# ──────────────────────────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ──────────────────────────────────────────────────────────
# I18N / TZ (unchanged)
# ──────────────────────────────────────────────────────────
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kuala_Lumpur'
USE_I18N = True
USE_TZ = True

# ──────────────────────────────────────────────────────────
# Static files (Render + WhiteNoise)
# ──────────────────────────────────────────────────────────
# URL is /static/ (note leading and trailing slash)
STATIC_URL = '/static/'

if DEBUG:
    # Your existing dev static dir
    STATICFILES_DIRS = [BASE_DIR / 'static']
else:
    # Where collectstatic will place files on Render
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    # Enable compressed, hashed filenames for long-term caching
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ──────────────────────────────────────────────────────────
# Defaults / CORS (unchanged)
# ──────────────────────────────────────────────────────────
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = ["http://127.0.0.1:8000", "http://localhost:3000"]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = ["authorization", "content-type", "x-csrftoken"]
# CORS_ALLOW_ALL_ORIGINS = False  # keep your current stance
